// Generated by scripts/generate-third-party-notices.sh from LICENSE and
// THIRD-PARTY-NOTICES.txt; do not edit by hand.
enum ThirdPartyNotices {
    static let appLicense = #"""
MIT License

Copyright (c) 2026 Cyberneura

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""#

    static let text = #"""
THIRD-PARTY NOTICES

Vocelo bundles no third-party libraries. Generated by
scripts/generate-third-party-notices.sh; do not edit by hand.

Vocelo is built from its own sources (MIT License, see LICENSE), the Swift
standard library, and Apple's system frameworks (AppKit, Carbon, Speech,
AVFoundation, ApplicationServices). The Swift runtime and the frameworks are
part of macOS and are not distributed with the app. The small parts of the
Swift toolchain that are linked into the executable are covered by the Runtime
Library Exception to the Apache License 2.0, which does not require attribution
for compiled code.
"""#
}
