#!/bin/bash
# Writes THIRD-PARTY-NOTICES.txt, and Sources/Vocelo/ThirdPartyNotices.swift which embeds
# the same text, and the app's own LICENSE, in the binary for the "Third-Party Licenses…"
# menu item.
#
#   scripts/generate-third-party-notices.sh           # rewrite both files
#   scripts/generate-third-party-notices.sh --check   # exit 1 if either is out of date
#
# Vocelo has no package dependencies: it is built from its own sources, the Swift
# standard library and Apple's frameworks. So what this writes is the statement that
# nothing third-party is bundled, and the script's real job is to refuse to write that
# statement once it stops being true. Adding a `.package(...)` to Package.swift (or a
# Package.resolved with pins) makes it fail until it is taught to list those packages
# from Package.resolved and their .build/checkouts/<name>/LICENSE files.
#
# The text is embedded as generated Swift rather than a SwiftPM resource because
# scripts/build-app.sh copies only the executable into the bundle; Bundle.module would
# not find a resource bundle there and traps.
#
# Runs on Linux and on the bash 3.2 that ships with macOS.
set -euo pipefail
cd "$(dirname "$0")/.."

mode=write
case "${1:-}" in
    "") ;;
    --check) mode=check ;;
    *)
        echo "Usage: scripts/generate-third-party-notices.sh [--check]" >&2
        exit 1
        ;;
esac

NOTICES="THIRD-PARTY-NOTICES.txt"
SWIFT="Sources/Vocelo/ThirdPartyNotices.swift"

# Where SwiftPM is at hand (macOS, and so CI) the manifest is evaluated and its
# dependency list read, which no formatting of Package.swift can get past. Elsewhere
# the text is searched: `//` comments dropped so a commented-out dependency does not
# count, lines joined so `.package` and its `(` on different lines still match, and
# `.package(` rather than `dependencies:` so target dependencies do not. A block
# comment mentioning `.package(` is a false alarm, which is the safe way to be wrong.
if command -v swift > /dev/null 2>&1 && command -v python3 > /dev/null 2>&1; then
    manifest=$(swift package --disable-sandbox dump-package)
    count=$(printf '%s' "$manifest" \
        | python3 -c 'import json, sys; print(len(json.load(sys.stdin)["dependencies"]))')
    has_dependencies=$([[ "$count" != 0 ]] && echo yes || echo no)
elif sed -e 's://.*$::' Package.swift | tr '\n' ' ' | grep -Eq '\.package[[:space:]]*\('; then
    has_dependencies=yes
else
    has_dependencies=no
fi
if [[ "$has_dependencies" == yes ]]; then
    echo "Error: Package.swift declares package dependencies. Extend this script to write a" >&2
    echo "'# Swift packages' section from Package.resolved and .build/checkouts/*/LICENSE*." >&2
    exit 1
fi
if [[ -f Package.resolved ]] && grep -q '"identity"' Package.resolved; then
    echo "Error: Package.resolved pins packages. Extend this script to list them." >&2
    exit 1
fi

# Temporary files sit next to their targets: an mv across file systems is a copy,
# and a copy cut short leaves a broken file behind.
notices_tmp=$(mktemp "$NOTICES.XXXXXX")
swift_tmp=$(mktemp "$SWIFT.XXXXXX")
trap 'rm -f "$notices_tmp" "$swift_tmp"' EXIT

cat > "$notices_tmp" <<'EOF'
THIRD-PARTY NOTICES

Vocelo bundles no third-party libraries. Generated by
scripts/generate-third-party-notices.sh; do not edit by hand.

Vocelo is built from its own sources (MIT License, see LICENSE), the Swift
standard library, and Apple's system frameworks (AppKit, Carbon, Speech,
AVFoundation, ApplicationServices). The Swift runtime and the frameworks are
part of macOS and are not distributed with the app. The small parts of the
Swift toolchain that are linked into the executable are covered by the Runtime
Library Exception to the Apache License 2.0, which does not require attribution
for compiled code.
EOF

# Raw strings, so a backslash or quote in a license text is taken as written. The one
# sequence that would end them early is refused rather than escaped.
for text in LICENSE "$notices_tmp"; do
    if grep -q '"""#' "$text"; then
        echo "Error: $text contains '\"\"\"#', which would end the Swift raw string." >&2
        exit 1
    fi
done
# The app's own license goes in as well: only the executable is copied into the bundle,
# so the LICENSE file never reaches someone who installed the app.
{
    echo '// Generated by scripts/generate-third-party-notices.sh from LICENSE and'
    echo '// THIRD-PARTY-NOTICES.txt; do not edit by hand.'
    echo 'enum ThirdPartyNotices {'
    echo '    static let appLicense = #"""'
    tr -d '\r' < LICENSE
    echo '"""#'
    echo ''
    echo '    static let text = #"""'
    cat "$notices_tmp"
    echo '"""#'
    echo '}'
} > "$swift_tmp"

if [[ "$mode" == check ]]; then
    stale=0
    for pair in "$notices_tmp:$NOTICES" "$swift_tmp:$SWIFT"; do
        generated="${pair%%:*}"
        committed="${pair#*:}"
        # CRLF is tolerated: a checkout with autocrlf is not a stale file.
        if [[ ! -f "$committed" ]] || ! diff -q <(tr -d '\r' < "$committed") "$generated" > /dev/null; then
            echo "$committed is out of date; run scripts/generate-third-party-notices.sh and commit it." >&2
            if [[ -f "$committed" ]]; then
                diff -u <(tr -d '\r' < "$committed") "$generated" >&2 || true
            fi
            stale=1
        fi
    done
    exit "$stale"
fi

mv "$notices_tmp" "$NOTICES"
mv "$swift_tmp" "$SWIFT"
printf 'Wrote %s and %s\n' "$NOTICES" "$SWIFT"
